services:
  php:
    build:
      context: ./docker/php
    container_name: web-php
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    networks:
      - dev
  db:
    image: mariadb:11
    container_name: web-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: web-pma
    ports:
      - "8080:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: db
    networks:
      - dev
  nginx:
    image: nginx:1.25
    container_name: web-server
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - dev
  mail:
    image: mailhog/mailhog
    container_name: web-mail
    ports:
      - "8025:8025"
    networks:
      - dev
  node:
    build:
      context: ./docker/node
    container_name: web-assets
    command: sh -c "pnpm i && pnpm dev"
    ports:
      - "5173:5173"
    volumes:
      - .:/home/node/app
    networks:
      - dev

volumes:
  mysql_data:

networks:
  dev:
    driver: bridge
